{% set python_min = '3.10' %}
{% set name = "timml" %}
{% set version = "6.6.0" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82cca07ca2c49ab6a7f1ae53c9bec0bb35c041deacd7b6363dc88f0b0f07953c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numba >=0.50.1
    - numpy >=1.15
    - scipy >=0.19
    - matplotlib-base >=2.0
  run:
    - python >={{ python_min }}
    - {{ pin_compatible('numpy') }}
    - numba >=0.50.1
    - scipy >=0.19
    - matplotlib-base >=2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - timml

about:
  home: https://github.com/mbakker7/timml
  license: MIT
  license_file: LICENSE
  summary: TimML is a multi-layer analytic element model
  dev_url: https://github.com/mbakker7/timml

extra:
  recipe-maintainers:
    - dbrakenhoff
    - mbakker7
    - jentjr
    - Huite
