{% set name = "timml" %}
{% set version = "6.5.0" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e43f566ffbc4b0fb48a681ef73222a03d477d230ee0d5f49c667f3575742182

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
    - numba >=0.50.1
    - numpy >=1.15
    - scipy >=0.19
    - matplotlib-base >=2.0
  run:
    - python >=3.10
    - {{ pin_compatible('numpy') }}
    - numba >=0.50.1
    - scipy >=0.19
    - matplotlib-base >=2.0

test:
  imports:
    - timml

about:
  home: https://github.com/mbakker7/timml
  license: MIT
  license_file: LICENSE
  summary: TimML is a multi-layer analytic element model
  dev_url: https://github.com/mbakker7/timml

extra:
  recipe-maintainers:
    - dbrakenhoff
    - mbakker7
    - jentjr
    - Huite
