{% set name = "timml" %}
{% set version = "6.1.0" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 232ed8395b1e16fc29a7ff5ff1a813873bfff86ef2263cbc23dade4aca1ad32b

build:
  number: 2
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - numba >=0.50.1
    - numpy >=1.15
    - scipy >=0.19
    - matplotlib-base >=2.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numba >=0.50.1
    - scipy >=0.19
    - matplotlib-base >=2.0

test:
  imports:
    - timml

about:
  home: https://github.com/mbakker7/timml
  license: MIT
  license_file: LICENSE
  summary: TimML is a multi-layer analytic element model
  dev_url: https://github.com/mbakker7/timml

extra:
  recipe-maintainers:
    - mbakker7
    - jentjr
    - Huite
