{% set name = "timml" %}
{% set version = "6.4.1" %}

package:
  name: {{ name |lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c4915863d7f59d66087b01d746b91e05dd5e4f1f71dced683dff9ef01b44eaa

build:
  number: 2
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - numba >=0.50.1
    - numpy >=1.15
    - scipy >=0.19
    - matplotlib-base >=2.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numba >=0.50.1
    - scipy >=0.19
    - matplotlib-base >=2.0

test:
  imports:
    - timml

about:
  home: https://github.com/mbakker7/timml
  license: MIT
  license_file: LICENSE
  summary: TimML is a multi-layer analytic element model
  dev_url: https://github.com/mbakker7/timml

extra:
  recipe-maintainers:
    - mbakker7
    - jentjr
    - Huite
